import { extensionProtocolVersion, isJsonObject, parseExtensionCommand, type ExtensionCommand as ShimCommand, type JsonObject } from "../../src/protocol.ts"
import { encodeRecordingFrame } from "../../src/recording-protocol.ts"
import type {
  OffscreenCancelRecordingResult,
  OffscreenOutgoingMessage,
  OffscreenStartRecordingResult,
  OffscreenStatusRecordingResult,
  OffscreenStopRecordingResult,
} from "./recording-types.ts"
import { finalizeBrowserControlGrouping, formatTabGroupTitle, isAutoGeneratedSessionId, isBrowserControlGroupTitle, tabGroupColor } from "./tab-groups.ts"
import { pageStatusFromJson } from "./page-status.ts"
import { debuggerDetachedEvent } from "./debugger-detach.ts"
import { getOwnedDebuggerTabIds } from "./debugger-ownership.ts"
import { completeExtensionHandshake, reconnectAlarmName, startConnectionLifecycle, startSocketKeepAlive } from "./connection-lifecycle.ts"

const relayHost = "127.0.0.1"
const relayPort = 19989
const offscreenDocumentPath = "offscreen.html"
const maxRecordingSocketBufferedBytes = 16 * 1024 * 1024

let socket: WebSocket | undefined
let connectionPromise: Promise<void> | undefined
let reconnectTimer: ReturnType<typeof setTimeout> | undefined
let offscreenDocumentCreating: Promise<void> | undefined
let groupReconciliation: Promise<void> | undefined
let socketGeneration = 0
let reloading = false
const tabGroupingCommands = new Map<number, Promise<unknown>>()
const sessionGroups = new Map<string, number>()
const agentGroups = new Set<number>()
const waitingTabs = new Set<number>()
const runningTabs = new Set<number>()
const attachedTabUrls = new Map<number, string>()
let collapseDebounceTimer: ReturnType<typeof setTimeout> | undefined

const STORAGE_ATTACHED_TABS_KEY = "browserControlAttachedTabs"
const STORAGE_AGENT_GROUPS_KEY = "browserControlAgentGroups"
let storageRestored: Promise<void> | undefined

async function readStoredJson<T>(key: string, fallback: T): Promise<T> {
  if (typeof caches === "undefined") return fallback
  try {
    const cache = await caches.open("browser-control-v1")
    const response = await cache.match(`https://state.invalid/${key}`)
    return response ? ((await response.json()) as T) : fallback
  } catch {
    return fallback
  }
}

function writeStoredJson(key: string, value: unknown): void {
  if (typeof caches === "undefined") return
  void caches
    .open("browser-control-v1")
    .then((cache) => cache.put(`https://state.invalid/${key}`, new Response(JSON.stringify(value))))
    .catch(() => {})
}

function restorePersistentState(): Promise<void> {
  storageRestored ??= Promise.all([
    readStoredJson<number[]>(STORAGE_AGENT_GROUPS_KEY, []),
    readStoredJson<{ readonly tabId?: unknown; readonly url?: unknown }[]>(STORAGE_ATTACHED_TABS_KEY, []),
  ])
    .then(([savedGroups, savedTabs]) => {
      for (const id of savedGroups) {
        if (typeof id === "number") agentGroups.add(id)
      }
      for (const item of savedTabs) {
        if (typeof item?.tabId === "number" && typeof item?.url === "string" && !attachedTabUrls.has(item.tabId)) {
          attachedTabUrls.set(item.tabId, item.url)
        }
      }
    })
    .catch(() => {})
  return storageRestored
}

function saveAgentGroups(): void {
  if (reloading) return
  writeStoredJson(STORAGE_AGENT_GROUPS_KEY, Array.from(agentGroups))
}

function saveAttachedTabUrls(): void {
  if (reloading) return
  const entries = Array.from(attachedTabUrls, ([tabId, url]) => ({ tabId, url }))
  writeStoredJson(STORAGE_ATTACHED_TABS_KEY, entries)
}

async function recordAttachedTab(tabId: number): Promise<void> {
  await restorePersistentState()
  const tab = await chrome.tabs.get(tabId).catch(() => undefined)
  if (tab?.url) {
    attachedTabUrls.set(tabId, tab.url)
    saveAttachedTabUrls()
  }
}

function forgetAttachedTab(tabId: number): void {
  if (reloading) return
  if (attachedTabUrls.delete(tabId)) {
    saveAttachedTabUrls()
  }
}

class ConnectionChangedError extends Error {}

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name !== reconnectAlarmName) {
    return
  }
  void ensureConnection().catch(() => {})
})

startConnectionLifecycle({
  alarms: chrome.alarms,
  addStartupListener: (listener) => chrome.runtime.onStartup.addListener(listener),
  addInstalledListener: (listener) => chrome.runtime.onInstalled.addListener(listener),
  connect,
})

chrome.action.onClicked.addListener((tab) => {
  if (tab.id) sendMessage({ method: "toolbar.clicked", params: { tabId: tab.id } })
})

chrome.debugger.onEvent.addListener((source, method, params) => {
  if (!source.tabId) {
    return
  }
  const rawParams = toJsonObject(params)
  let eventParams = rawParams
  if (method === "Page.screencastFrame" && typeof rawParams.sessionId === "number") {
    void chrome.debugger.sendCommand(source, "Page.screencastFrameAck", { sessionId: rawParams.sessionId }).catch(() => {})
    eventParams = { ...rawParams, acked: true }
  }
  sendMessage({
    method: "debugger.event",
    params: {
      tabId: source.tabId,
      method,
      params: eventParams,
      ...(source.sessionId === undefined ? {} : { sessionId: source.sessionId }),
    },
  })
})

const explicitlyDetachingTabs = new Set<number>()

async function recoverTabDebugger(tabId: number, requireEviction: boolean): Promise<boolean> {
  const evicted = (await chrome.tabs.sendMessage(tabId, { action: "evict-extension-frames" }).catch(() => undefined)) as { readonly removed?: number } | undefined
  if (requireEviction && (evicted?.removed ?? 0) === 0) return false
  await new Promise((resolve) => setTimeout(resolve, 45))
  const owned = await getOwnedDebuggerTabIds(chrome.debugger)
  if (owned.has(tabId)) return true
  return await chrome.debugger.attach({ tabId }, "1.3").then(() => true, (error) => isAlreadyAttachedError(error))
}

chrome.debugger.onDetach.addListener((source, reason) => {
  if (reloading || !source.tabId) {
    return
  }
  const tabId = source.tabId
  const sessionId = (source as chrome.debugger.DebuggerSession).sessionId
  if (sessionId === undefined && !explicitlyDetachingTabs.has(tabId)) {
    void (async () => {
      const tab = await chrome.tabs.get(tabId).catch(() => undefined)
      if (tab && (await recoverTabDebugger(tabId, reason !== "target_closed"))) {
        sendMessage(debuggerDetachedEvent({ tabId, reason: "target_closed", sessionId }))
        return
      }
      forgetAttachedTab(tabId)
      sendMessage(debuggerDetachedEvent({ tabId, reason, sessionId }))
    })()
    return
  }
  if (sessionId === undefined) {
    forgetAttachedTab(tabId)
  }
  sendMessage(debuggerDetachedEvent({
    tabId,
    reason,
    sessionId,
  }))
})

chrome.tabs.onRemoved.addListener((tabId) => {
  waitingTabs.delete(tabId)
  runningTabs.delete(tabId)
  forgetAttachedTab(tabId)
  void cleanupRecordingForTab(tabId)
  void guardedUngroupBrowserControlTab(tabId)
  sendMessage({ method: "tabs.removed", params: { tabId } })
})

chrome.runtime.onStartup.addListener(() => {
  agentGroups.clear()
  attachedTabUrls.clear()
  writeStoredJson(STORAGE_AGENT_GROUPS_KEY, [])
  writeStoredJson(STORAGE_ATTACHED_TABS_KEY, [])
})

chrome.tabs.onActivated.addListener(({ tabId, windowId }) => {
  if (collapseDebounceTimer) clearTimeout(collapseDebounceTimer)
  collapseDebounceTimer = setTimeout(() => {
    collapseDebounceTimer = undefined
    if (tabGroupingCommands.size > 0) return
    void restorePersistentState().then(async () => {
      const activeTab = await chrome.tabs.get(tabId).catch(() => undefined)
      for (const groupId of Array.from(agentGroups)) {
        if (activeTab?.groupId === groupId) continue
        const group = await chrome.tabGroups.get(groupId).catch(() => undefined)
        if (!group) {
          if (agentGroups.delete(groupId)) saveAgentGroups()
        } else if (group.windowId === windowId && !group.collapsed && !(await isGroupWaiting(groupId))) {
          await chrome.tabGroups.update(groupId, { collapsed: true }).catch(() => {})
        }
      }
    })
  }, 250)
})

chrome.tabGroups?.onRemoved.addListener((group) => {
  if (agentGroups.delete(group.id)) saveAgentGroups()
})

chrome.tabs.onUpdated.addListener((tabId, change) => {
  if (!change.url && !change.title) return
  if (attachedTabUrls.has(tabId)) {
    if (change.url) {
      attachedTabUrls.set(tabId, change.url)
      saveAttachedTabUrls()
    }
    void renameAutoGroupForPage(tabId, change.url)
  }
})
void restorePersistentState()

chrome.runtime.onMessage.addListener((message: unknown, sender, sendResponse) => {
  void handleRuntimeMessage(message, sender).then(
    () => sendResponse({ success: true }),
    (error: unknown) => sendResponse({ success: false, error: error instanceof Error ? error.message : String(error) }),
  )
  return true
})

function connect(): void {
  void ensureConnection().catch(() => {})
}

function startConnection(): WebSocket {
  if (reconnectTimer) {
    clearTimeout(reconnectTimer)
    reconnectTimer = undefined
  }
  const currentSocket = new WebSocket(`ws://${relayHost}:${relayPort}/extension`)
  const currentGeneration = ++socketGeneration
  let stopKeepAlive: (() => void) | undefined
  socket = currentSocket
  currentSocket.onopen = () => {
    void announceHelloAndAttachedTabs(currentSocket, currentGeneration).then(
      () => {
        if (socket === currentSocket && currentSocket.readyState === WebSocket.OPEN) {
          stopKeepAlive = startSocketKeepAlive(() => sendOnCurrentSocket(currentSocket, { method: "pong" }))
        }
      },
      (error) => reportAnnouncementFailure(currentSocket, error),
    )
  }
  currentSocket.onmessage = (event) => {
    void handleSocketMessage(currentSocket, event.data)
  }
  currentSocket.onclose = () => {
    stopKeepAlive?.()
    if (socket !== currentSocket) {
      return
    }
    void cancelAllRecordings()
    socket = undefined
    reconnectTimer = setTimeout(connect, 1000)
  }
  return currentSocket
}

async function ensureConnection(): Promise<void> {
  if (socket?.readyState === WebSocket.OPEN) {
    return
  }
  if (connectionPromise) {
    return connectionPromise
  }
  const current = socket?.readyState === WebSocket.CONNECTING ? socket : startConnection()
  const pending = new Promise<void>((resolve, reject) => {
    if (current.readyState === WebSocket.OPEN) {
      resolve()
      return
    }
    let timeout: ReturnType<typeof setTimeout>
    const cleanup = () => {
      clearTimeout(timeout)
      current.removeEventListener("open", onOpen)
      current.removeEventListener("error", onError)
      current.removeEventListener("close", onClose)
    }
    const onOpen = () => {
      cleanup()
      resolve()
    }
    const onError = () => {
      cleanup()
      reject(new Error("Relay connection failed"))
    }
    const onClose = () => {
      cleanup()
      reject(new Error("Relay connection closed"))
    }
    timeout = setTimeout(() => {
      cleanup()
      current.close()
      reject(new Error("Relay connection timed out"))
    }, 5000)
    current.addEventListener("open", onOpen, { once: true })
    current.addEventListener("error", onError, { once: true })
    current.addEventListener("close", onClose, { once: true })
  })
  connectionPromise = pending
  try {
    await pending
  } finally {
    if (connectionPromise === pending) connectionPromise = undefined
  }
}

async function announceHelloAndAttachedTabs(currentSocket: WebSocket, currentGeneration: number): Promise<void> {
  sendOnSocket(currentSocket, {
    method: "hello",
    params: {
      version: chrome.runtime.getManifest().version,
      protocolVersion: extensionProtocolVersion,
    },
  })
  await completeExtensionHandshake({
    announceAttachedTabs: () => reannounceAttachedTabs(currentSocket),
    sendReady: () => sendOnSocket(currentSocket, { method: "ready" }),
    startGroupReconciliation: () => startGroupReconciliation(currentGeneration),
  })
}

function reportAnnouncementFailure(currentSocket: WebSocket, error: unknown): void {
  if (socket !== currentSocket || currentSocket.readyState !== WebSocket.OPEN) return
  currentSocket.send(JSON.stringify({ method: "log", params: { level: "error", message: `Failed to re-announce attached tabs: ${error instanceof Error ? error.message : String(error)}` } }))
  currentSocket.close(1011, "Attached-tab inventory failed")
}

function startGroupReconciliation(currentGeneration: number): void {
  if (groupReconciliation) return
  const pending = reconcileBrowserControlGroups(currentGeneration)
    .catch((error: unknown) => {
      if (error instanceof ConnectionChangedError || currentGeneration !== socketGeneration) return
      const currentSocket = socket
      if (!currentSocket) return
      sendOnCurrentSocket(currentSocket, {
        method: "log",
        params: {
          level: "error",
          message: `Failed to reconcile tab groups: ${error instanceof Error ? error.message : String(error)}`,
        },
      })
    })
    .finally(() => {
      if (groupReconciliation !== pending) return
      groupReconciliation = undefined
      if (currentGeneration !== socketGeneration && socket?.readyState === WebSocket.OPEN) {
        startGroupReconciliation(socketGeneration)
      }
    })
  groupReconciliation = pending
}

async function reannounceAttachedTabs(currentSocket: WebSocket): Promise<void> {
  await restorePersistentState()
  const ownedBefore = await getOwnedDebuggerTabIds(chrome.debugger)
  for (const [tabId, storedUrl] of Array.from(attachedTabUrls)) {
    if (ownedBefore.has(tabId)) continue
    const tab = await chrome.tabs.get(tabId).catch(() => undefined)
    if (!tab || !storedUrl || tab.url !== storedUrl) {
      attachedTabUrls.delete(tabId)
      continue
    }
    await chrome.debugger.attach({ tabId }, "1.3").catch(() => {})
  }
  const ownedNow = await getOwnedDebuggerTabIds(chrome.debugger)
  for (const tabId of ownedNow) {
    await recordAttachedTab(tabId)
    sendOnSocket(currentSocket, { method: "debugger.attached", params: { tabId } })
  }
}

function sendOnSocket(currentSocket: WebSocket, message: JsonObject): void {
  assertCurrentSocket(currentSocket)
  currentSocket.send(JSON.stringify(message))
}

async function handleSocketMessage(currentSocket: WebSocket, data: unknown): Promise<void> {
  let command: ShimCommand
  try {
    command = parseExtensionCommand(String(data))
  } catch (error) {
    sendOnCurrentSocket(currentSocket, { method: "log", params: { level: "error", message: error instanceof Error ? error.message : String(error) } })
    return
  }
  try {
    const result = await handleCommand(command, currentSocket)
    sendOnCurrentSocket(currentSocket, { id: command.id, result })
  } catch (error) {
    sendOnCurrentSocket(currentSocket, { id: command.id, error: error instanceof Error ? error.message : String(error) })
  }
}

function sendOnCurrentSocket(currentSocket: WebSocket, message: JsonObject): void {
  if (isCurrentSocket(currentSocket)) {
    currentSocket.send(JSON.stringify(message))
  }
}

async function handleCommand(command: ShimCommand, currentSocket: WebSocket): Promise<JsonObject> {
  if (command.method === "ping") {
    return {}
  }
  if (command.method === "debugger.attach") {
    const tabId = numberParam(command.params, "tabId")
    try {
      await chrome.debugger.attach({ tabId }, "1.3")
    } catch (error) {
      if (!isAlreadyAttachedError(error)) {
        throw error
      }
    }
    void recordAttachedTab(tabId)
    return {}
  }
  if (command.method === "debugger.detach") {
    const tabId = numberParam(command.params, "tabId")
    forgetAttachedTab(tabId)
    explicitlyDetachingTabs.add(tabId)
    try {
      await chrome.debugger.detach({ tabId })
    } finally {
      explicitlyDetachingTabs.delete(tabId)
    }
    await runTabGroupingCommand(tabId, () => guardedUngroupBrowserControlTab(tabId, {
      assertCurrent: () => assertCurrentSocket(currentSocket),
    }))
    return {}
  }
  if (command.method === "debugger.sendCommand") {
    const tabId = numberParam(command.params, "tabId")
    const cdpMethod = stringParam(command.params, "method")
    const params = objectParam(command.params, "params")
    const sessionId = optionalStringParam(command.params, "sessionId")
    const debuggee: chrome.debugger.DebuggerSession = { tabId, ...(sessionId === undefined ? {} : { sessionId }) }
    try {
      return toJsonObject(await chrome.debugger.sendCommand(debuggee, cdpMethod, params))
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      if (/Cannot access a chrome-extension:\/\/ URL|Debugger is not attached to the tab/i.test(message)) {
        for (let attempt = 0; attempt < 2; attempt += 1) {
          await recoverTabDebugger(tabId, false)
          try {
            return toJsonObject(await chrome.debugger.sendCommand(debuggee, cdpMethod, params))
          } catch (retryError) {
            const retryMsg = retryError instanceof Error ? retryError.message : String(retryError)
            if (!/Cannot access a chrome-extension:\/\/ URL|Debugger is not attached to the tab/i.test(retryMsg)) {
              throw retryError
            }
          }
        }
        if (sessionId === undefined && cdpMethod === "Page.navigate" && typeof params?.url === "string") {
          await chrome.tabs.update(tabId, { url: params.url })
          return { frameId: String(tabId) }
        }
      }
      throw error
    }
  }
  if (command.method === "tabs.create") {
    const url = optionalStringParam(command.params, "url") ?? "about:blank"
    const active = optionalBooleanParam(command.params, "active") ?? false
    const tab = await chrome.tabs.create({ url, active })
    if (!tab.id) {
      throw new Error("Created tab has no id")
    }
    return { tabId: tab.id }
  }
  if (command.method === "tabs.remove") {
    const tabId = numberParam(command.params, "tabId")
    await chrome.tabs.remove(tabId)
    return {}
  }
  if (command.method === "tabs.group") {
    const tabId = numberParam(command.params, "tabId")
    const sessionId = typeof command.params?.sessionId === "string" ? command.params.sessionId : undefined
    return await runTabGroupingCommand(tabId, () => groupBrowserControlTab(tabId, currentSocket, sessionId))
  }
  if (command.method === "tabs.ungroup") {
    const tabId = numberParam(command.params, "tabId")
    await runTabGroupingCommand(tabId, () => guardedUngroupBrowserControlTab(tabId, {
      assertCurrent: () => assertCurrentSocket(currentSocket),
    }))
    return {}
  }
  if (command.method === "action.setAttached") {
    const tabId = numberParam(command.params, "tabId")
    const attached = Boolean(command.params?.attached)
    await setTabBadge(tabId, attached ? "ON" : "", "#7c3aed", attached ? "Detach from Browser Control" : "Attach to Browser Control")
    return {}
  }
  if (command.method === "action.setBadge") {
    const tabId = numberParam(command.params, "tabId")
    await setTabBadge(
      tabId,
      optionalStringParam(command.params, "text") ?? "",
      optionalStringParam(command.params, "color") ?? "#7c3aed",
      optionalStringParam(command.params, "title"),
    )
    return {}
  }
  if (command.method === "pageStatus.set") {
    const tabId = numberParam(command.params, "tabId")
    const status = pageStatusFromJson(objectParam(command.params, "status"))
    if (!status) {
      throw new Error("Invalid page status")
    }
    if (status.state === "running") runningTabs.add(tabId)
    else runningTabs.delete(tabId)
    const wasWaiting = waitingTabs.has(tabId)
    if (status.state === "waiting") {
      waitingTabs.add(tabId)
      void expandTabGroup(tabId)
    } else if (wasWaiting) {
      waitingTabs.delete(tabId)
      void settleTabGroup(tabId)
    }
    await sendPageStatusMessage(tabId, { action: "page-status.set", status }, true)
    return {}
  }
  if (command.method === "pageStatus.clear") {
    const tabId = numberParam(command.params, "tabId")
    runningTabs.delete(tabId)
    if (waitingTabs.delete(tabId)) {
      void settleTabGroup(tabId)
    }
    await sendPageStatusMessage(tabId, { action: "page-status.clear" })
    return {}
  }
  if (command.method === "runtime.reload") {
    reloading = true
    setTimeout(() => {
      currentSocket.close(1001, "Extension reloading")
      chrome.runtime.reload()
    }, 50)
    return {}
  }
  if (command.method === "recording.start") {
    return startRecording(command.params)
  }
  if (command.method === "recording.stop") {
    return stopRecording(command.params)
  }
  if (command.method === "recording.status") {
    return statusRecording(command.params)
  }
  if (command.method === "recording.cancel") {
    return cancelRecordingForTab(numberParam(command.params, "tabId"))
  }
  throw new Error(`Unknown shim command: ${command.method}`)
}

async function setTabBadge(tabId: number, text: string, color: string, title?: string): Promise<void> {
  await chrome.action.setBadgeText({ tabId, text })
  await chrome.action.setBadgeBackgroundColor({ tabId, color })
  if (title !== undefined) {
    await chrome.action.setTitle({ tabId, title })
  }
}

async function startRecording(params: JsonObject | undefined): Promise<JsonObject> {
  const tabId = numberParam(params, "tabId")
  await ensureOffscreenDocument()
  const streamId = await getTabCaptureStreamId(tabId)
  const result = await chrome.runtime.sendMessage({
    action: "recording.start",
    tabId,
    streamId,
    frameRate: optionalNumberParam(params, "frameRate") ?? 30,
    videoBitsPerSecond: optionalNumberParam(params, "videoBitsPerSecond") ?? 2_500_000,
    audioBitsPerSecond: optionalNumberParam(params, "audioBitsPerSecond") ?? 128_000,
    audio: optionalBooleanParam(params, "audio") ?? false,
  }) as OffscreenStartRecordingResult
  if (!result.success) {
    return { success: false, error: result.error }
  }
  return { success: true, tabId: result.tabId, startedAt: result.startedAt, mimeType: result.mimeType }
}

async function stopRecording(params: JsonObject | undefined): Promise<JsonObject> {
  const tabId = numberParam(params, "tabId")
  const result = await chrome.runtime.sendMessage({ action: "recording.stop", tabId }) as OffscreenStopRecordingResult
  if (!result.success) {
    return { success: false, error: result.error }
  }
  return { success: true, tabId: result.tabId, duration: result.duration }
}

async function statusRecording(params: JsonObject | undefined): Promise<JsonObject> {
  const tabId = numberParam(params, "tabId")
  const result = await chrome.runtime.sendMessage({ action: "recording.status", tabId }) as OffscreenStatusRecordingResult
  return {
    isRecording: result.isRecording,
    tabId,
    ...(result.startedAt === undefined ? {} : { startedAt: result.startedAt }),
  }
}

async function cancelRecordingForTab(tabId: number): Promise<JsonObject> {
  const result = await chrome.runtime.sendMessage({ action: "recording.cancel", tabId }) as OffscreenCancelRecordingResult
  if (!result.success) {
    return { success: false, error: result.error }
  }
  return { success: true }
}

async function cleanupRecordingForTab(tabId: number): Promise<void> {
  try {
    await cancelRecordingForTab(tabId)
  } catch {}
}

async function cancelAllRecordings(): Promise<void> {
  await chrome.runtime.sendMessage({ action: "recording.cancelAll" }).catch(() => {})
}

async function ensureOffscreenDocument(): Promise<void> {
  const documentUrl = chrome.runtime.getURL(offscreenDocumentPath)
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: [chrome.runtime.ContextType.OFFSCREEN_DOCUMENT],
    documentUrls: [documentUrl],
  })
  if (existingContexts.length > 0) {
    return
  }
  if (offscreenDocumentCreating) {
    return offscreenDocumentCreating
  }
  offscreenDocumentCreating = chrome.offscreen.createDocument({
    url: offscreenDocumentPath,
    reasons: [chrome.offscreen.Reason.USER_MEDIA],
    justification: "Record Browser Control tabs with chrome.tabCapture and MediaRecorder",
  })
  try {
    await offscreenDocumentCreating
  } finally {
    offscreenDocumentCreating = undefined
  }
}

async function getTabCaptureStreamId(tabId: number): Promise<string> {
  try {
    return await chrome.tabCapture.getMediaStreamId({ targetTabId: tabId })
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    if (message.includes("Extension has not been invoked") || message.includes("activeTab")) {
      throw new Error(`${message}. Click the Browser Control extension icon on this tab once before recording.`)
    }
    throw error
  }
}

async function reconcileBrowserControlGroups(currentGeneration: number): Promise<void> {
  if (!chrome.tabGroups) {
    return
  }
  const groups = await chrome.tabGroups.query({})
  assertCurrentGeneration(currentGeneration)
  const attachedTabIds = await getOwnedDebuggerTabIds(chrome.debugger)
  assertCurrentGeneration(currentGeneration)
  for (const group of groups) {
    if (!isBrowserControlGroupTitle(group.title)) {
      continue
    }
    const tabs = await chrome.tabs.query({ groupId: group.id })
    assertCurrentGeneration(currentGeneration)
    for (const tab of tabs) {
      if (typeof tab.id !== "number") {
        continue
      }
      const tabId = tab.id
      if (attachedTabIds.has(tabId)) {
        continue
      }
      await runTabGroupingCommand(tabId, () => guardedUngroupBrowserControlTab(tabId, {
        assertCurrent: () => assertCurrentGeneration(currentGeneration),
        preserveAttached: true,
      }))
    }
  }
}

async function isGroupWaiting(groupId: number): Promise<boolean> {
  if (waitingTabs.size === 0 && runningTabs.size === 0) return false
  const tabs = await chrome.tabs.query({ groupId }).catch(() => [] as chrome.tabs.Tab[])
  return tabs.some((tab) => typeof tab.id === "number" && (waitingTabs.has(tab.id) || runningTabs.has(tab.id)))
}

async function collapseGroupUnlessActive(groupId: number): Promise<void> {
  const group = await chrome.tabGroups.get(groupId).catch(() => undefined)
  if (!group) {
    if (agentGroups.delete(groupId)) saveAgentGroups()
    return
  }
  if (group.collapsed) return
  const [active] = await chrome.tabs.query({ active: true, windowId: group.windowId }).catch(() => [] as chrome.tabs.Tab[])
  if (active?.groupId === groupId || (await isGroupWaiting(groupId))) return
  await chrome.tabGroups.update(groupId, { collapsed: true }).catch(() => {})
}

function adoptAgentGroup(groupId: number): void {
  if (!agentGroups.has(groupId)) {
    agentGroups.add(groupId)
    saveAgentGroups()
  }
}

async function expandTabGroup(tabId: number): Promise<void> {
  const tab = await chrome.tabs.get(tabId).catch(() => undefined)
  if (tab && tab.groupId !== undefined && tab.groupId !== chrome.tabGroups.TAB_GROUP_ID_NONE && agentGroups.has(tab.groupId)) {
    await chrome.tabGroups.update(tab.groupId, { collapsed: false }).catch(() => {})
  }
}

async function settleTabGroup(tabId: number): Promise<void> {
  const tab = await chrome.tabs.get(tabId).catch(() => undefined)
  if (tab && tab.groupId !== undefined && tab.groupId !== chrome.tabGroups.TAB_GROUP_ID_NONE && agentGroups.has(tab.groupId)) {
    await collapseGroupUnlessActive(tab.groupId)
  }
}

async function renameAutoGroupForPage(tabId: number, url?: string): Promise<void> {
  const tab = await chrome.tabs.get(tabId).catch(() => undefined)
  if (!tab || tab.groupId === undefined || tab.groupId === chrome.tabGroups.TAB_GROUP_ID_NONE) return
  const sessionId = Array.from(sessionGroups).find(([, id]) => id === tab.groupId)?.[0]
  if (sessionId === undefined || !isAutoGeneratedSessionId(sessionId)) return
  const currentGroup = await chrome.tabGroups.get(tab.groupId).catch(() => undefined)
  const desiredTitle = formatTabGroupTitle(sessionId, url ?? tab.url, tab.title)
  if (currentGroup && isBrowserControlGroupTitle(currentGroup.title) && currentGroup.title !== desiredTitle) {
    await chrome.tabGroups.update(currentGroup.id, { title: desiredTitle, color: tabGroupColor }).catch(() => {})
  }
}

async function groupBrowserControlTab(
  tabId: number,
  currentSocket: WebSocket,
  sessionId?: string,
): Promise<JsonObject> {
  const tab = await chrome.tabs.get(tabId)
  const desiredTitle = formatTabGroupTitle(sessionId, tab.url, tab.title)
  const sessionKey = sessionId ?? ""
  const knownGroupId = sessionGroups.get(sessionKey)
  if (knownGroupId !== undefined) {
    const knownGroup = await chrome.tabGroups.get(knownGroupId).catch(() => undefined)
    if (knownGroup && knownGroup.windowId === tab.windowId && isBrowserControlGroupTitle(knownGroup.title)) {
      if (tab.groupId !== knownGroup.id) {
        await chrome.tabs.group({ tabIds: [tabId], groupId: knownGroup.id })
      }
      if (knownGroup.title !== desiredTitle || knownGroup.color !== tabGroupColor) {
        await chrome.tabGroups.update(knownGroup.id, { title: desiredTitle, color: tabGroupColor })
      }
      adoptAgentGroup(knownGroup.id)
      return { groupId: knownGroup.id }
    }
  }
  if (tab.groupId !== undefined && tab.groupId !== chrome.tabGroups.TAB_GROUP_ID_NONE) {
    const currentGroup = await chrome.tabGroups.get(tab.groupId)
    if (currentGroup.title === desiredTitle && currentGroup.color === tabGroupColor) {
      sessionGroups.set(sessionKey, currentGroup.id)
      adoptAgentGroup(currentGroup.id)
      return { groupId: currentGroup.id }
    }
    if (isBrowserControlGroupTitle(currentGroup.title)) {
      const groupedTabs = await chrome.tabs.query({ groupId: currentGroup.id })
      if (groupedTabs.length === 1 && groupedTabs[0]?.id === tabId) {
        await chrome.tabGroups.update(currentGroup.id, { title: desiredTitle, color: tabGroupColor })
        sessionGroups.set(sessionKey, currentGroup.id)
        adoptAgentGroup(currentGroup.id)
        return { groupId: currentGroup.id }
      }
    }
  }
  const groups = await chrome.tabGroups.query({ windowId: tab.windowId })
  assertCurrentSocket(currentSocket)
  const attachedTabIds = await getOwnedDebuggerTabIds(chrome.debugger)
  assertCurrentSocket(currentSocket)
  let existingGroup: chrome.tabGroups.TabGroup | undefined
  for (const group of groups) {
    if (group.title !== desiredTitle || group.color !== tabGroupColor) continue
    const groupedTabs = await chrome.tabs.query({ groupId: group.id })
    if (groupedTabs.some((groupedTab) => typeof groupedTab.id === "number" && attachedTabIds.has(groupedTab.id))) {
      existingGroup = group
      break
    }
  }
  assertCurrentSocket(currentSocket)
  const groupId = await chrome.tabs.group({
    tabIds: [tabId],
    ...(existingGroup ? { groupId: existingGroup.id } : {}),
  })
  await finalizeBrowserControlGrouping({
    assertCurrent: () => assertCurrentSocket(currentSocket),
    update: () => chrome.tabGroups.update(groupId, { title: desiredTitle, color: tabGroupColor }).then(() => {}),
    rollback: () => chrome.tabs.ungroup(tabId),
  })
  sessionGroups.set(sessionKey, groupId)
  adoptAgentGroup(groupId)
  return { groupId }
}

async function runTabGroupingCommand<A>(tabId: number, command: () => Promise<A>): Promise<A> {
  const previous = tabGroupingCommands.get(tabId) ?? Promise.resolve()
  const current = previous.catch(() => {}).then(command)
  tabGroupingCommands.set(tabId, current)
  try {
    return await current
  } finally {
    if (tabGroupingCommands.get(tabId) === current) tabGroupingCommands.delete(tabId)
  }
}

async function guardedUngroupBrowserControlTab(tabId: number, options: {
  readonly assertCurrent?: () => void
  readonly preserveAttached?: boolean
} = {}): Promise<void> {
  if (reloading) return
  const assertCurrent = options.assertCurrent ?? (() => {})
  try {
    const tab = await chrome.tabs.get(tabId)
    assertCurrent()
    if (tab.groupId === undefined || tab.groupId === chrome.tabGroups.TAB_GROUP_ID_NONE) {
      return
    }
    let groupTitle: string | undefined
    if (chrome.tabGroups) {
      const group = await chrome.tabGroups.get(tab.groupId)
      groupTitle = group.title
      assertCurrent()
    }
    if (!isBrowserControlGroupTitle(groupTitle)) {
      return
    }
    if (options.preserveAttached && (await getOwnedDebuggerTabIds(chrome.debugger)).has(tabId)) {
      return
    }
    assertCurrent()
    await chrome.tabs.ungroup(tabId)
  } catch (error) {
    if (error instanceof ConnectionChangedError) throw error
    // Tabs and groups can disappear while detach/close/reconnect cleanup is racing
    // the browser. Ungrouping is best-effort because stale groups are reconciled
    // again on service-worker startup and relay reconnect.
  }
}

function assertCurrentSocket(currentSocket: WebSocket): void {
  if (!isCurrentSocket(currentSocket)) throw new ConnectionChangedError("Extension connection changed")
}

function isCurrentSocket(currentSocket: WebSocket): boolean {
  return socket === currentSocket && currentSocket.readyState === WebSocket.OPEN
}

function assertCurrentGeneration(currentGeneration: number): void {
  if (currentGeneration !== socketGeneration || socket?.readyState !== WebSocket.OPEN) {
    throw new ConnectionChangedError("Extension connection changed")
  }
}

async function handleRuntimeMessage(message: unknown, sender: chrome.runtime.MessageSender): Promise<void> {
  if (!isJsonObject(message)) {
    return
  }
  const pageStatusMessage = message as { readonly action?: unknown; readonly handoffId?: unknown }
  if (pageStatusMessage.action === "page-status.ready") {
    if (typeof sender.tab?.id === "number") {
      sendMessage({ method: "pageStatus.requested", params: { tabId: sender.tab.id } })
    }
    return
  }
  if (pageStatusMessage.action === "handoff.complete") {
    if (typeof sender.tab?.id === "number" && typeof pageStatusMessage.handoffId === "string") {
      sendMessage({ method: "handoff.completed", params: { tabId: sender.tab.id, handoffId: pageStatusMessage.handoffId } })
    }
    return
  }
  const offscreenMessage = message as OffscreenOutgoingMessage
  if (offscreenMessage.action === "recording.chunk") {
    await sendBinaryAfterConnection(encodeRecordingFrame({
      tabId: offscreenMessage.tabId,
      sequence: offscreenMessage.sequence,
      final: offscreenMessage.final,
      payload: offscreenMessage.final ? new Uint8Array() : decodeBase64(offscreenMessage.dataBase64),
    }))
    return
  }
  if (offscreenMessage.action === "recording.cancelled") {
    sendMessage({ method: "recording.cancelled", params: { tabId: offscreenMessage.tabId } })
  }
}

async function sendPageStatusMessage(tabId: number, message: JsonObject, required = false): Promise<void> {
  try {
    await chrome.tabs.sendMessage(tabId, message)
  } catch (error) {
    if (required) throw error
    // Restricted pages do not accept content scripts. Visibility is best-effort
    // and must never interfere with debugger attachment or detachment.
  }
}

function sendMessage(message: JsonObject): void {
  void sendMessageAfterConnection(message).catch(() => {})
}

async function sendMessageAfterConnection(message: JsonObject): Promise<void> {
  const connected = openSocket()
  if (connected) {
    connected.send(JSON.stringify(message))
    return
  }
  await ensureConnection()
  openSocket()?.send(JSON.stringify(message))
}

function openSocket(): WebSocket | undefined {
  const current = socket
  return current?.readyState === WebSocket.OPEN ? current : undefined
}

async function sendBinaryAfterConnection(data: Uint8Array): Promise<void> {
  if (socket?.readyState !== WebSocket.OPEN) await ensureConnection()
  const currentSocket = socket
  if (currentSocket?.readyState !== WebSocket.OPEN) throw new Error("Browser Control relay is not connected")
  const deadline = Date.now() + 30_000
  while (currentSocket.bufferedAmount + data.byteLength > maxRecordingSocketBufferedBytes) {
    await new Promise((resolve) => setTimeout(resolve, 10))
    if (socket !== currentSocket || currentSocket.readyState !== WebSocket.OPEN) {
      throw new Error("Browser Control relay disconnected while sending recording data")
    }
    if (Date.now() >= deadline) throw new Error("Timed out sending recording data to the Browser Control relay")
  }
  currentSocket.send(new Uint8Array(data))
}

function decodeBase64(value: string): Uint8Array {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index)
  return bytes
}

function isAlreadyAttachedError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error)
  return message.includes("Another debugger is already attached") || message.includes("Debugger is already attached")
}

function numberParam(params: JsonObject | undefined, key: string): number {
  const value = params?.[key]
  if (typeof value !== "number") {
    throw new Error(`Missing number param: ${key}`)
  }
  return value
}

function stringParam(params: JsonObject | undefined, key: string): string {
  const value = params?.[key]
  if (typeof value !== "string") {
    throw new Error(`Missing string param: ${key}`)
  }
  return value
}

function optionalStringParam(params: JsonObject | undefined, key: string): string | undefined {
  const value = params?.[key]
  return typeof value === "string" ? value : undefined
}

function optionalBooleanParam(params: JsonObject | undefined, key: string): boolean | undefined {
  const value = params?.[key]
  return typeof value === "boolean" ? value : undefined
}

function optionalNumberParam(params: JsonObject | undefined, key: string): number | undefined {
  const value = params?.[key]
  return typeof value === "number" ? value : undefined
}

function objectParam(params: JsonObject | undefined, key: string): JsonObject | undefined {
  const value = params?.[key]
  return isJsonObject(value) ? value : undefined
}

function toJsonObject(value: unknown): JsonObject {
  return isJsonObject(value) ? value : {}
}
