import { extensionProtocolVersion, isJsonObject, parseExtensionCommand, type ExtensionCommand as ShimCommand, type JsonObject } from "../../src/protocol.ts"
import { encodeRecordingFrame } from "../../src/recording-protocol.ts"
import type {
  OffscreenCancelRecordingResult,
  OffscreenOutgoingMessage,
  OffscreenStartRecordingResult,
  OffscreenStatusRecordingResult,
  OffscreenStopRecordingResult,
} from "./recording-types.ts"
import { finalizeBrowserControlGrouping, formatTabGroupTitle, isAutoGeneratedSessionId, isBrowserControlGroupTitle, tabGroupColor } from "./tab-groups.ts"
import { pageStatusFromJson } from "./page-status.ts"
import { debuggerDetachedEvent } from "./debugger-detach.ts"
import { getOwnedDebuggerTabIds } from "./debugger-ownership.ts"
import { completeExtensionHandshake, reconnectAlarmName, startConnectionLifecycle, startSocketKeepAlive } from "./connection-lifecycle.ts"

const relayHost = "127.0.0.1"
const relayPort = 19989
const offscreenDocumentPath = "offscreen.html"
const maxRecordingSocketBufferedBytes = 16 * 1024 * 1024

let socket: WebSocket | undefined
let connectionPromise: Promise<void> | undefined
let reconnectTimer: ReturnType<typeof setTimeout> | undefined
let offscreenDocumentCreating: Promise<void> | undefined
let groupReconciliation: Promise<void> | undefined
let socketGeneration = 0
let reloading = false
const tabGroupingCommands = new Map<number, Promise<unknown>>()
const sessionGroups = new Map<string, number>()
const attachedTabUrls = new Map<number, string>()
const pendingTabRequests = new Map<string, (approved: boolean) => void>()

const STORAGE_ATTACHED_TABS_KEY = "browserControlAttachedTabs"
let storageRestored: Promise<void> | undefined

async function readStoredJson<T>(key: string, fallback: T): Promise<T> {
  if (typeof caches === "undefined") return fallback
  try {
    const cache = await caches.open("browser-control-v1")
    const response = await cache.match(`https://state.invalid/${key}`)
    return response ? ((await response.json()) as T) : fallback
  } catch {
    return fallback
  }
}

function writeStoredJson(key: string, value: unknown): void {
  if (typeof caches === "undefined") return
  void caches
    .open("browser-control-v1")
    .then((cache) => cache.put(`https://state.invalid/${key}`, new Response(JSON.stringify(value))))
    .catch(() => {})
}

function restorePersistentState(): Promise<void> {
  storageRestored ??= readStoredJson<{ readonly tabId?: unknown; readonly url?: unknown }[]>(
    STORAGE_ATTACHED_TABS_KEY,
    [],
  )
    .then((savedTabs) => {
      for (const item of savedTabs) {
        if (typeof item?.tabId === "number" && typeof item?.url === "string" && !attachedTabUrls.has(item.tabId)) {
          attachedTabUrls.set(item.tabId, item.url)
        }
      }
    })
    .catch(() => {})
  return storageRestored
}

function saveAttachedTabUrls(): void {
  if (reloading) return
  const entries = Array.from(attachedTabUrls, ([tabId, url]) => ({ tabId, url }))
  writeStoredJson(STORAGE_ATTACHED_TABS_KEY, entries)
}

async function recordAttachedTab(tabId: number): Promise<void> {
  await restorePersistentState()
  const tab = await chrome.tabs.get(tabId).catch(() => undefined)
  attachedTabUrls.set(tabId, tab?.url || "about:blank")
  saveAttachedTabUrls()
}

function forgetAttachedTab(tabId: number): void {
  if (reloading) return
  if (attachedTabUrls.delete(tabId)) {
    saveAttachedTabUrls()
  }
}

class ConnectionChangedError extends Error {}

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name !== reconnectAlarmName) {
    return
  }
  void ensureConnection().catch(() => {})
})

startConnectionLifecycle({
  alarms: chrome.alarms,
  addStartupListener: (listener) => chrome.runtime.onStartup.addListener(listener),
  addInstalledListener: (listener) => chrome.runtime.onInstalled.addListener(listener),
  connect,
})

chrome.action.onClicked.addListener((tab) => {
  if (tab.id) sendMessage({ method: "toolbar.clicked", params: { tabId: tab.id } })
})

chrome.debugger.onEvent.addListener((source, method, params) => {
  if (!source.tabId) {
    return
  }
  const rawParams = toJsonObject(params)
  let eventParams = rawParams
  if (method === "Page.screencastFrame" && typeof rawParams.sessionId === "number") {
    void chrome.debugger.sendCommand(source, "Page.screencastFrameAck", { sessionId: rawParams.sessionId }).catch(() => {})
    eventParams = { ...rawParams, acked: true }
  }
  sendMessage({
    method: "debugger.event",
    params: {
      tabId: source.tabId,
      method,
      params: eventParams,
      ...(source.sessionId === undefined ? {} : { sessionId: source.sessionId }),
    },
  })
})

const explicitlyDetachingTabs = new Set<number>()

async function recoverTabDebugger(tabId: number, requireEviction: boolean): Promise<boolean> {
  const evicted = (await chrome.tabs.sendMessage(tabId, { action: "evict-extension-frames" }).catch(() => undefined)) as { readonly removed?: number } | undefined
  if (requireEviction && (evicted?.removed ?? 0) === 0) return false
  await new Promise((resolve) => setTimeout(resolve, 45))
  const owned = await getOwnedDebuggerTabIds(chrome.debugger)
  if (owned.has(tabId)) return true
  const attached = await chrome.debugger.attach({ tabId }, "1.3").then(() => true, (error) => isAlreadyAttachedError(error))
  if (attached) {
    await Promise.all([
      chrome.debugger.sendCommand({ tabId }, "Page.enable", {}).catch(() => {}),
      chrome.debugger.sendCommand({ tabId }, "Page.setLifecycleEventsEnabled", { enabled: true }).catch(() => {}),
      chrome.debugger.sendCommand({ tabId }, "Runtime.enable", {}).catch(() => {}),
      chrome.debugger.sendCommand({ tabId }, "Network.enable", {}).catch(() => {}),
      chrome.debugger.sendCommand({ tabId }, "Emulation.setFocusEmulationEnabled", { enabled: true }).catch(() => {}),
      chrome.debugger.sendCommand({ tabId }, "Target.setAutoAttach", { autoAttach: true, waitForDebuggerOnStart: false, flatten: true }).catch(() => {}),
    ])
  }
  return attached
}

async function navigateViaTabsUpdateFallback(
  tabId: number,
  url: string,
  requestedFrameId: string | undefined,
  currentSocket: WebSocket,
): Promise<JsonObject> {
  const beforeTab = await chrome.tabs.get(tabId).catch(() => undefined)
  const previousUrl = beforeTab?.url
  await chrome.tabs.update(tabId, { url })
  const deadline = Date.now() + 12_000
  let frameObj: JsonObject | undefined
  while (Date.now() < deadline) {
    await new Promise((resolve) => setTimeout(resolve, 60))
    const tab = await chrome.tabs.get(tabId).catch(() => undefined)
    if (!tab) break
    await recoverTabDebugger(tabId, false)
    try {
      const tree = toJsonObject(await chrome.debugger.sendCommand({ tabId }, "Page.getFrameTree", {}))
      const frameTree = objectParam(tree, "frameTree")
      const candidate = objectParam(frameTree, "frame")
      const currentUrl = typeof candidate?.url === "string" ? candidate.url : tab.url
      const urlAdvanced = !previousUrl || previousUrl === url || currentUrl !== previousUrl
      if (candidate && currentUrl && currentUrl !== "about:blank" && urlAdvanced && tab.status === "complete") {
        frameObj = candidate
        break
      }
      if (candidate && urlAdvanced) frameObj = candidate
    } catch {
      // Wait for navigation away from extension-tainted document to finish
    }
  }
  const frameId =
    (typeof frameObj?.id === "string" ? frameObj.id : undefined) ??
    requestedFrameId ??
    String(tabId)
  const loaderId =
    (typeof frameObj?.loaderId === "string" ? frameObj.loaderId : undefined) ??
    `tabs-update-${Date.now()}`
  const finalUrl = (typeof frameObj?.url === "string" ? frameObj.url : undefined) ?? url
  const synthesizedFrame: JsonObject = frameObj ?? {
    id: frameId,
    loaderId,
    url: finalUrl,
    domainAndRegistry: "",
    securityOrigin: "",
    mimeType: "text/html",
  }
  // 1. Emit Page.frameNavigated FIRST so the relay re-keys mainFrame._id in Playwright
  // before any new execution contexts or lifecycle events arrive.
  sendOnCurrentSocket(currentSocket, {
    method: "debugger.event",
    params: {
      tabId,
      method: "Page.frameNavigated",
      params: { frame: synthesizedFrame, type: "TabsUpdateFallback" },
    },
  })
  // 2. Now re-enable Runtime so Chrome emits Runtime.executionContextCreated for the new mainFrameId.
  await chrome.debugger.sendCommand({ tabId }, "Page.enable", {}).catch(() => {})
  await chrome.debugger.sendCommand({ tabId }, "Page.setLifecycleEventsEnabled", { enabled: true }).catch(() => {})
  await chrome.debugger.sendCommand({ tabId }, "Runtime.disable", {}).catch(() => {})
  await chrome.debugger.sendCommand({ tabId }, "Runtime.enable", {}).catch(() => {})
  await new Promise((resolve) => setTimeout(resolve, 60))
  // 3. Emit lifecycle events after contexts are registered.
  const ts = Date.now() / 1_000
  for (const name of ["commit", "DOMContentLoaded", "load", "networkAlmostIdle", "networkIdle"]) {
    sendOnCurrentSocket(currentSocket, {
      method: "debugger.event",
      params: {
        tabId,
        method: "Page.lifecycleEvent",
        params: { frameId, loaderId, name, timestamp: ts },
      },
    })
  }
  return { frameId, loaderId }
}

chrome.debugger.onDetach.addListener((source, reason) => {
  if (reloading || !source.tabId) {
    return
  }
  const tabId = source.tabId
  const sessionId = (source as chrome.debugger.DebuggerSession).sessionId
  if (sessionId === undefined && !explicitlyDetachingTabs.has(tabId)) {
    void (async () => {
      const tab = await chrome.tabs.get(tabId).catch(() => undefined)
      if (tab && (await recoverTabDebugger(tabId, reason !== "target_closed"))) {
        sendMessage(debuggerDetachedEvent({ tabId, reason: "target_closed", sessionId }))
        return
      }
      forgetAttachedTab(tabId)
      sendMessage(debuggerDetachedEvent({ tabId, reason, sessionId }))
    })()
    return
  }
  if (sessionId === undefined) {
    forgetAttachedTab(tabId)
  }
  sendMessage(debuggerDetachedEvent({
    tabId,
    reason,
    sessionId,
  }))
})

chrome.tabs.onCreated.addListener((tab) => {
  const tabId = tab.id
  const openerTabId = tab.openerTabId
  if (tabId === undefined || openerTabId === undefined || !attachedTabUrls.has(openerTabId)) {
    return
  }
  void (async () => {
    try {
      await chrome.debugger.attach({ tabId }, "1.3")
    } catch (error) {
      if (!isAlreadyAttachedError(error)) {
        return
      }
    }
    await recordAttachedTab(tabId)
    sendMessage({ method: "debugger.attached", params: { tabId, openerTabId } })
  })()
})

chrome.tabs.onRemoved.addListener((tabId) => {
  forgetAttachedTab(tabId)
  void cleanupRecordingForTab(tabId)
  void guardedUngroupBrowserControlTab(tabId)
  sendMessage({ method: "tabs.removed", params: { tabId } })
})

chrome.runtime.onStartup.addListener(() => {
  attachedTabUrls.clear()
  writeStoredJson(STORAGE_ATTACHED_TABS_KEY, [])
})

chrome.tabs.onUpdated.addListener((tabId, change) => {
  if (!change.url && !change.title) return
  if (attachedTabUrls.has(tabId)) {
    if (change.url) {
      attachedTabUrls.set(tabId, change.url)
      saveAttachedTabUrls()
    }
    void renameAutoGroupForPage(tabId, change.url)
  }
})
void restorePersistentState()

chrome.runtime.onMessage.addListener((message: unknown, sender, sendResponse) => {
  void handleRuntimeMessage(message, sender).then(
    () => sendResponse({ success: true }),
    (error: unknown) => sendResponse({ success: false, error: error instanceof Error ? error.message : String(error) }),
  )
  return true
})

function connect(): void {
  void ensureConnection().catch(() => {})
}

function startConnection(): WebSocket {
  if (reconnectTimer) {
    clearTimeout(reconnectTimer)
    reconnectTimer = undefined
  }
  const currentSocket = new WebSocket(`ws://${relayHost}:${relayPort}/extension`)
  const currentGeneration = ++socketGeneration
  let stopKeepAlive: (() => void) | undefined
  socket = currentSocket
  currentSocket.onopen = () => {
    void announceHelloAndAttachedTabs(currentSocket, currentGeneration).then(
      () => {
        if (socket === currentSocket && currentSocket.readyState === WebSocket.OPEN) {
          stopKeepAlive = startSocketKeepAlive(() => sendOnCurrentSocket(currentSocket, { method: "pong" }))
        }
      },
      (error) => reportAnnouncementFailure(currentSocket, error),
    )
  }
  currentSocket.onmessage = (event) => {
    void handleSocketMessage(currentSocket, event.data)
  }
  currentSocket.onclose = () => {
    stopKeepAlive?.()
    if (socket !== currentSocket) {
      return
    }
    void cancelAllRecordings()
    socket = undefined
    reconnectTimer = setTimeout(connect, 1000)
  }
  return currentSocket
}

async function ensureConnection(): Promise<void> {
  if (socket?.readyState === WebSocket.OPEN) {
    return
  }
  if (connectionPromise) {
    return connectionPromise
  }
  const current = socket?.readyState === WebSocket.CONNECTING ? socket : startConnection()
  const pending = new Promise<void>((resolve, reject) => {
    if (current.readyState === WebSocket.OPEN) {
      resolve()
      return
    }
    let timeout: ReturnType<typeof setTimeout>
    const cleanup = () => {
      clearTimeout(timeout)
      current.removeEventListener("open", onOpen)
      current.removeEventListener("error", onError)
      current.removeEventListener("close", onClose)
    }
    const onOpen = () => {
      cleanup()
      resolve()
    }
    const onError = () => {
      cleanup()
      reject(new Error("Relay connection failed"))
    }
    const onClose = () => {
      cleanup()
      reject(new Error("Relay connection closed"))
    }
    timeout = setTimeout(() => {
      cleanup()
      current.close()
      reject(new Error("Relay connection timed out"))
    }, 5000)
    current.addEventListener("open", onOpen, { once: true })
    current.addEventListener("error", onError, { once: true })
    current.addEventListener("close", onClose, { once: true })
  })
  connectionPromise = pending
  try {
    await pending
  } finally {
    if (connectionPromise === pending) connectionPromise = undefined
  }
}

async function announceHelloAndAttachedTabs(currentSocket: WebSocket, currentGeneration: number): Promise<void> {
  sendOnSocket(currentSocket, {
    method: "hello",
    params: {
      version: chrome.runtime.getManifest().version,
      protocolVersion: extensionProtocolVersion,
    },
  })
  await completeExtensionHandshake({
    announceAttachedTabs: () => reannounceAttachedTabs(currentSocket),
    sendReady: () => sendOnSocket(currentSocket, { method: "ready" }),
    startGroupReconciliation: () => startGroupReconciliation(currentGeneration),
  })
}

function reportAnnouncementFailure(currentSocket: WebSocket, error: unknown): void {
  if (socket !== currentSocket || currentSocket.readyState !== WebSocket.OPEN) return
  currentSocket.send(JSON.stringify({ method: "log", params: { level: "error", message: `Failed to re-announce attached tabs: ${error instanceof Error ? error.message : String(error)}` } }))
  currentSocket.close(1011, "Attached-tab inventory failed")
}

function startGroupReconciliation(currentGeneration: number): void {
  if (groupReconciliation) return
  const pending = reconcileBrowserControlGroups(currentGeneration)
    .catch((error: unknown) => {
      if (error instanceof ConnectionChangedError || currentGeneration !== socketGeneration) return
      const currentSocket = socket
      if (!currentSocket) return
      sendOnCurrentSocket(currentSocket, {
        method: "log",
        params: {
          level: "error",
          message: `Failed to reconcile tab groups: ${error instanceof Error ? error.message : String(error)}`,
        },
      })
    })
    .finally(() => {
      if (groupReconciliation !== pending) return
      groupReconciliation = undefined
      if (currentGeneration !== socketGeneration && socket?.readyState === WebSocket.OPEN) {
        startGroupReconciliation(socketGeneration)
      }
    })
  groupReconciliation = pending
}

async function reannounceAttachedTabs(currentSocket: WebSocket): Promise<void> {
  await restorePersistentState()
  const ownedBefore = await getOwnedDebuggerTabIds(chrome.debugger)
  for (const [tabId, storedUrl] of Array.from(attachedTabUrls)) {
    if (ownedBefore.has(tabId)) continue
    const tab = await chrome.tabs.get(tabId).catch(() => undefined)
    if (!tab || !storedUrl || (storedUrl !== "about:blank" && tab.url !== storedUrl)) {
      attachedTabUrls.delete(tabId)
      continue
    }
    await chrome.debugger.attach({ tabId }, "1.3").catch(() => {})
  }
  const ownedNow = await getOwnedDebuggerTabIds(chrome.debugger)
  for (const tabId of ownedNow) {
    await recordAttachedTab(tabId)
    sendOnSocket(currentSocket, { method: "debugger.attached", params: { tabId } })
  }
}

function sendOnSocket(currentSocket: WebSocket, message: JsonObject): void {
  assertCurrentSocket(currentSocket)
  currentSocket.send(JSON.stringify(message))
}

async function handleSocketMessage(currentSocket: WebSocket, data: unknown): Promise<void> {
  let command: ShimCommand
  try {
    command = parseExtensionCommand(String(data))
  } catch (error) {
    sendOnCurrentSocket(currentSocket, { method: "log", params: { level: "error", message: error instanceof Error ? error.message : String(error) } })
    return
  }
  try {
    const result = await handleCommand(command, currentSocket)
    sendOnCurrentSocket(currentSocket, { id: command.id, result })
  } catch (error) {
    sendOnCurrentSocket(currentSocket, { id: command.id, error: error instanceof Error ? error.message : String(error) })
  }
}

function sendOnCurrentSocket(currentSocket: WebSocket, message: JsonObject): void {
  if (isCurrentSocket(currentSocket)) {
    currentSocket.send(JSON.stringify(message))
  }
}

async function handleCommand(command: ShimCommand, currentSocket: WebSocket): Promise<JsonObject> {
  if (command.method === "ping") {
    return {}
  }
  if (command.method === "debugger.attach") {
    const tabId = numberParam(command.params, "tabId")
    try {
      await chrome.debugger.attach({ tabId }, "1.3")
    } catch (error) {
      if (!isAlreadyAttachedError(error)) {
        throw error
      }
    }
    void recordAttachedTab(tabId)
    return {}
  }
  if (command.method === "debugger.detach") {
    const tabId = numberParam(command.params, "tabId")
    forgetAttachedTab(tabId)
    explicitlyDetachingTabs.add(tabId)
    try {
      await chrome.debugger.detach({ tabId })
    } finally {
      explicitlyDetachingTabs.delete(tabId)
    }
    await runTabGroupingCommand(tabId, () => guardedUngroupBrowserControlTab(tabId, {
      assertCurrent: () => assertCurrentSocket(currentSocket),
    }))
    return {}
  }
  if (command.method === "debugger.sendCommand") {
    const tabId = numberParam(command.params, "tabId")
    const cdpMethod = stringParam(command.params, "method")
    const params = objectParam(command.params, "params")
    const sessionId = optionalStringParam(command.params, "sessionId")
    const debuggee: chrome.debugger.DebuggerSession = { tabId, ...(sessionId === undefined ? {} : { sessionId }) }
    try {
      return toJsonObject(await chrome.debugger.sendCommand(debuggee, cdpMethod, params))
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      if (/Cannot access a chrome-extension:\/\/ URL|Debugger is not attached to the tab/i.test(message)) {
        for (let attempt = 0; attempt < 2; attempt += 1) {
          await recoverTabDebugger(tabId, false)
          try {
            return toJsonObject(await chrome.debugger.sendCommand(debuggee, cdpMethod, params))
          } catch (retryError) {
            const retryMsg = retryError instanceof Error ? retryError.message : String(retryError)
            if (!/Cannot access a chrome-extension:\/\/ URL|Debugger is not attached to the tab/i.test(retryMsg)) {
              throw retryError
            }
          }
        }
        if (sessionId === undefined && cdpMethod === "Page.navigate" && typeof params?.url === "string") {
          return await navigateViaTabsUpdateFallback(
            tabId,
            params.url,
            optionalStringParam(params, "frameId"),
            currentSocket,
          )
        }
      }
      throw error
    }
  }
  if (command.method === "tabs.create") {
    const url = optionalStringParam(command.params, "url") ?? "about:blank"
    const active = optionalBooleanParam(command.params, "active") ?? false
    const tab = await chrome.tabs.create({ url, active })
    if (!tab.id) {
      throw new Error("Created tab has no id")
    }
    return { tabId: tab.id }
  }
  if (command.method === "tabs.remove") {
    const tabId = numberParam(command.params, "tabId")
    await chrome.tabs.remove(tabId)
    return {}
  }
  if (command.method === "tabs.group") {
    const tabId = numberParam(command.params, "tabId")
    const sessionId = typeof command.params?.sessionId === "string" ? command.params.sessionId : undefined
    return await runTabGroupingCommand(tabId, () => groupBrowserControlTab(tabId, currentSocket, sessionId))
  }
  if (command.method === "tabs.ungroup") {
    const tabId = numberParam(command.params, "tabId")
    await runTabGroupingCommand(tabId, () => guardedUngroupBrowserControlTab(tabId, {
      assertCurrent: () => assertCurrentSocket(currentSocket),
    }))
    return {}
  }
  if (command.method === "action.setAttached") {
    const tabId = numberParam(command.params, "tabId")
    const attached = Boolean(command.params?.attached)
    await setTabBadge(tabId, attached ? "ON" : "", "#7c3aed", attached ? "Detach from Browser Control" : "Attach to Browser Control")
    return {}
  }
  if (command.method === "action.setBadge") {
    const tabId = numberParam(command.params, "tabId")
    await setTabBadge(
      tabId,
      optionalStringParam(command.params, "text") ?? "",
      optionalStringParam(command.params, "color") ?? "#7c3aed",
      optionalStringParam(command.params, "title"),
    )
    return {}
  }
  if (command.method === "pageStatus.set") {
    const tabId = numberParam(command.params, "tabId")
    const status = pageStatusFromJson(objectParam(command.params, "status"))
    if (!status) {
      throw new Error("Invalid page status")
    }
    await sendPageStatusMessage(tabId, { action: "page-status.set", status }, true)
    return {}
  }
  if (command.method === "pageStatus.clear") {
    const tabId = numberParam(command.params, "tabId")
    await sendPageStatusMessage(tabId, { action: "page-status.clear" })
    return {}
  }
  if (command.method === "tabs.requestAttach") {
    return requestTabAttach(command.params)
  }
  if (command.method === "runtime.reload") {
    const owned = await getOwnedDebuggerTabIds(chrome.debugger).catch(() => new Set<number>())
    for (const tabId of owned) {
      await recordAttachedTab(tabId)
    }
    reloading = true
    setTimeout(() => {
      currentSocket.close(1000, "Extension reloading")
      chrome.runtime.reload()
    }, 50)
    return {}
  }
  if (command.method === "recording.start") {
    return startRecording(command.params)
  }
  if (command.method === "recording.stop") {
    return stopRecording(command.params)
  }
  if (command.method === "recording.status") {
    return statusRecording(command.params)
  }
  if (command.method === "recording.cancel") {
    return cancelRecordingForTab(numberParam(command.params, "tabId"))
  }
  throw new Error(`Unknown shim command: ${command.method}`)
}

async function setTabBadge(tabId: number, text: string, color: string, title?: string): Promise<void> {
  await chrome.action.setBadgeText({ tabId, text })
  await chrome.action.setBadgeBackgroundColor({ tabId, color })
  if (title !== undefined) {
    await chrome.action.setTitle({ tabId, title })
  }
}

async function startRecording(params: JsonObject | undefined): Promise<JsonObject> {
  const tabId = numberParam(params, "tabId")
  await ensureOffscreenDocument()
  const streamId = await getTabCaptureStreamId(tabId)
  const result = await chrome.runtime.sendMessage({
    action: "recording.start",
    tabId,
    streamId,
    frameRate: optionalNumberParam(params, "frameRate") ?? 30,
    videoBitsPerSecond: optionalNumberParam(params, "videoBitsPerSecond") ?? 2_500_000,
    audioBitsPerSecond: optionalNumberParam(params, "audioBitsPerSecond") ?? 128_000,
    audio: optionalBooleanParam(params, "audio") ?? false,
  }) as OffscreenStartRecordingResult
  if (!result.success) {
    return { success: false, error: result.error }
  }
  return { success: true, tabId: result.tabId, startedAt: result.startedAt, mimeType: result.mimeType }
}

async function stopRecording(params: JsonObject | undefined): Promise<JsonObject> {
  const tabId = numberParam(params, "tabId")
  const result = await chrome.runtime.sendMessage({ action: "recording.stop", tabId }) as OffscreenStopRecordingResult
  if (!result.success) {
    return { success: false, error: result.error }
  }
  return { success: true, tabId: result.tabId, duration: result.duration }
}

async function statusRecording(params: JsonObject | undefined): Promise<JsonObject> {
  const tabId = numberParam(params, "tabId")
  const result = await chrome.runtime.sendMessage({ action: "recording.status", tabId }) as OffscreenStatusRecordingResult
  return {
    isRecording: result.isRecording,
    tabId,
    ...(result.startedAt === undefined ? {} : { startedAt: result.startedAt }),
  }
}

async function cancelRecordingForTab(tabId: number): Promise<JsonObject> {
  const result = await chrome.runtime.sendMessage({ action: "recording.cancel", tabId }) as OffscreenCancelRecordingResult
  if (!result.success) {
    return { success: false, error: result.error }
  }
  return { success: true }
}

async function cleanupRecordingForTab(tabId: number): Promise<void> {
  try {
    await cancelRecordingForTab(tabId)
  } catch {}
}

async function cancelAllRecordings(): Promise<void> {
  await chrome.runtime.sendMessage({ action: "recording.cancelAll" }).catch(() => {})
}

async function ensureOffscreenDocument(): Promise<void> {
  const documentUrl = chrome.runtime.getURL(offscreenDocumentPath)
  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: [chrome.runtime.ContextType.OFFSCREEN_DOCUMENT],
    documentUrls: [documentUrl],
  })
  if (existingContexts.length > 0) {
    return
  }
  if (offscreenDocumentCreating) {
    return offscreenDocumentCreating
  }
  offscreenDocumentCreating = chrome.offscreen.createDocument({
    url: offscreenDocumentPath,
    reasons: [chrome.offscreen.Reason.USER_MEDIA],
    justification: "Record Browser Control tabs with chrome.tabCapture and MediaRecorder",
  })
  try {
    await offscreenDocumentCreating
  } finally {
    offscreenDocumentCreating = undefined
  }
}

async function getTabCaptureStreamId(tabId: number): Promise<string> {
  try {
    return await chrome.tabCapture.getMediaStreamId({ targetTabId: tabId })
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    if (message.includes("Extension has not been invoked") || message.includes("activeTab")) {
      throw new Error(`${message}. Click the Browser Control extension icon on this tab once before recording.`)
    }
    throw error
  }
}

async function reconcileBrowserControlGroups(currentGeneration: number): Promise<void> {
  if (!chrome.tabGroups) {
    return
  }
  const groups = await chrome.tabGroups.query({})
  assertCurrentGeneration(currentGeneration)
  const attachedTabIds = await getOwnedDebuggerTabIds(chrome.debugger)
  assertCurrentGeneration(currentGeneration)
  for (const group of groups) {
    if (!isBrowserControlGroupTitle(group.title)) {
      continue
    }
    if (group.collapsed) {
      await chrome.tabGroups.update(group.id, { collapsed: false }).catch(() => {})
    }
    const tabs = await chrome.tabs.query({ groupId: group.id })
    assertCurrentGeneration(currentGeneration)
    for (const tab of tabs) {
      if (typeof tab.id !== "number") {
        continue
      }
      const tabId = tab.id
      if (attachedTabIds.has(tabId)) {
        continue
      }
      await runTabGroupingCommand(tabId, () => guardedUngroupBrowserControlTab(tabId, {
        assertCurrent: () => assertCurrentGeneration(currentGeneration),
        preserveAttached: true,
      }))
    }
  }
}

async function renameAutoGroupForPage(tabId: number, url?: string): Promise<void> {
  const tab = await chrome.tabs.get(tabId).catch(() => undefined)
  if (!tab || tab.groupId === undefined || tab.groupId === chrome.tabGroups.TAB_GROUP_ID_NONE) return
  const sessionId = Array.from(sessionGroups).find(([, id]) => id === tab.groupId)?.[0]
  if (sessionId === undefined || !isAutoGeneratedSessionId(sessionId)) return
  const currentGroup = await chrome.tabGroups.get(tab.groupId).catch(() => undefined)
  const desiredTitle = formatTabGroupTitle(sessionId, url ?? tab.url, tab.title)
  if (currentGroup && isBrowserControlGroupTitle(currentGroup.title) && currentGroup.title !== desiredTitle) {
    await chrome.tabGroups.update(currentGroup.id, { title: desiredTitle, color: tabGroupColor }).catch(() => {})
  }
}

async function groupBrowserControlTab(
  tabId: number,
  currentSocket: WebSocket,
  sessionId?: string,
): Promise<JsonObject> {
  const tab = await chrome.tabs.get(tabId)
  const desiredTitle = formatTabGroupTitle(sessionId, tab.url, tab.title)
  const sessionKey = sessionId ?? ""
  const knownGroupId = sessionGroups.get(sessionKey)
  if (knownGroupId !== undefined) {
    const knownGroup = await chrome.tabGroups.get(knownGroupId).catch(() => undefined)
    if (knownGroup && knownGroup.windowId === tab.windowId && isBrowserControlGroupTitle(knownGroup.title)) {
      if (tab.groupId !== knownGroup.id) {
        await chrome.tabs.group({ tabIds: [tabId], groupId: knownGroup.id })
      }
      if (knownGroup.title !== desiredTitle || knownGroup.color !== tabGroupColor || knownGroup.collapsed) {
        await chrome.tabGroups.update(knownGroup.id, { title: desiredTitle, color: tabGroupColor, collapsed: false })
      }
      return { groupId: knownGroup.id }
    }
  }
  if (tab.groupId !== undefined && tab.groupId !== chrome.tabGroups.TAB_GROUP_ID_NONE) {
    const currentGroup = await chrome.tabGroups.get(tab.groupId)
    if (currentGroup.title === desiredTitle && currentGroup.color === tabGroupColor) {
      if (currentGroup.collapsed) {
        await chrome.tabGroups.update(currentGroup.id, { collapsed: false }).catch(() => {})
      }
      sessionGroups.set(sessionKey, currentGroup.id)
      return { groupId: currentGroup.id }
    }
    if (isBrowserControlGroupTitle(currentGroup.title)) {
      const groupedTabs = await chrome.tabs.query({ groupId: currentGroup.id })
      if (groupedTabs.length === 1 && groupedTabs[0]?.id === tabId) {
        await chrome.tabGroups.update(currentGroup.id, { title: desiredTitle, color: tabGroupColor, collapsed: false })
        sessionGroups.set(sessionKey, currentGroup.id)
        return { groupId: currentGroup.id }
      }
    }
  }
  const groups = await chrome.tabGroups.query({ windowId: tab.windowId })
  assertCurrentSocket(currentSocket)
  const attachedTabIds = await getOwnedDebuggerTabIds(chrome.debugger)
  assertCurrentSocket(currentSocket)
  let existingGroup: chrome.tabGroups.TabGroup | undefined
  for (const group of groups) {
    if (group.title !== desiredTitle || group.color !== tabGroupColor) continue
    const groupedTabs = await chrome.tabs.query({ groupId: group.id })
    if (groupedTabs.some((groupedTab) => typeof groupedTab.id === "number" && attachedTabIds.has(groupedTab.id))) {
      existingGroup = group
      break
    }
  }
  assertCurrentSocket(currentSocket)
  const groupId = await chrome.tabs.group({
    tabIds: [tabId],
    ...(existingGroup ? { groupId: existingGroup.id } : {}),
  })
  await finalizeBrowserControlGrouping({
    assertCurrent: () => assertCurrentSocket(currentSocket),
    update: () => chrome.tabGroups.update(groupId, { title: desiredTitle, color: tabGroupColor, collapsed: false }).then(() => {}),
    rollback: () => chrome.tabs.ungroup(tabId),
  })
  sessionGroups.set(sessionKey, groupId)
  return { groupId }
}

async function runTabGroupingCommand<A>(tabId: number, command: () => Promise<A>): Promise<A> {
  const previous = tabGroupingCommands.get(tabId) ?? Promise.resolve()
  const current = previous.catch(() => {}).then(command)
  tabGroupingCommands.set(tabId, current)
  try {
    return await current
  } finally {
    if (tabGroupingCommands.get(tabId) === current) tabGroupingCommands.delete(tabId)
  }
}

async function guardedUngroupBrowserControlTab(tabId: number, options: {
  readonly assertCurrent?: () => void
  readonly preserveAttached?: boolean
} = {}): Promise<void> {
  if (reloading) return
  const assertCurrent = options.assertCurrent ?? (() => {})
  try {
    const tab = await chrome.tabs.get(tabId)
    assertCurrent()
    if (tab.groupId === undefined || tab.groupId === chrome.tabGroups.TAB_GROUP_ID_NONE) {
      return
    }
    let groupTitle: string | undefined
    if (chrome.tabGroups) {
      const group = await chrome.tabGroups.get(tab.groupId)
      groupTitle = group.title
      assertCurrent()
    }
    if (!isBrowserControlGroupTitle(groupTitle)) {
      return
    }
    if (options.preserveAttached && (await getOwnedDebuggerTabIds(chrome.debugger)).has(tabId)) {
      return
    }
    assertCurrent()
    await chrome.tabs.ungroup(tabId)
  } catch (error) {
    if (error instanceof ConnectionChangedError) throw error
    // Tabs and groups can disappear while detach/close/reconnect cleanup is racing
    // the browser. Ungrouping is best-effort because stale groups are reconciled
    // again on service-worker startup and relay reconnect.
  }
}

function assertCurrentSocket(currentSocket: WebSocket): void {
  if (!isCurrentSocket(currentSocket)) throw new ConnectionChangedError("Extension connection changed")
}

function isCurrentSocket(currentSocket: WebSocket): boolean {
  return socket === currentSocket && currentSocket.readyState === WebSocket.OPEN
}

function assertCurrentGeneration(currentGeneration: number): void {
  if (currentGeneration !== socketGeneration || socket?.readyState !== WebSocket.OPEN) {
    throw new ConnectionChangedError("Extension connection changed")
  }
}

async function handleRuntimeMessage(message: unknown, sender: chrome.runtime.MessageSender): Promise<void> {
  if (!isJsonObject(message)) {
    return
  }
  const pageStatusMessage = message as { readonly action?: unknown; readonly handoffId?: unknown }
  if (pageStatusMessage.action === "page-status.ready") {
    if (typeof sender.tab?.id === "number") {
      sendMessage({ method: "pageStatus.requested", params: { tabId: sender.tab.id } })
    }
    return
  }
  if (pageStatusMessage.action === "handoff.complete") {
    if (typeof sender.tab?.id === "number" && typeof pageStatusMessage.handoffId === "string") {
      sendMessage({ method: "handoff.completed", params: { tabId: sender.tab.id, handoffId: pageStatusMessage.handoffId } })
    }
    return
  }
  const tabDecision = message as { readonly action?: unknown; readonly requestId?: unknown; readonly approved?: unknown }
  if (tabDecision.action === "tab-request.decision" && typeof tabDecision.requestId === "string") {
    const resolver = pendingTabRequests.get(tabDecision.requestId)
    if (resolver) {
      pendingTabRequests.delete(tabDecision.requestId)
      resolver(tabDecision.approved === true)
    }
    return
  }
  if (tabDecision.action === "tab.detach" && typeof sender.tab?.id === "number") {
    const detachTabId = sender.tab.id
    forgetAttachedTab(detachTabId)
    explicitlyDetachingTabs.add(detachTabId)
    try {
      await chrome.debugger.detach({ tabId: detachTabId }).catch(() => {})
    } finally {
      explicitlyDetachingTabs.delete(detachTabId)
    }
    await setTabBadge(detachTabId, "", "#7c3aed", "Attach to Browser Control").catch(() => {})
    await sendPageStatusMessage(detachTabId, { action: "page-status.clear" })
    sendMessage(debuggerDetachedEvent({ tabId: detachTabId, reason: "canceled_by_user" }))
    return
  }
  const offscreenMessage = message as OffscreenOutgoingMessage
  if (offscreenMessage.action === "recording.chunk") {
    await sendBinaryAfterConnection(encodeRecordingFrame({
      tabId: offscreenMessage.tabId,
      sequence: offscreenMessage.sequence,
      final: offscreenMessage.final,
      payload: offscreenMessage.final ? new Uint8Array() : decodeBase64(offscreenMessage.dataBase64),
    }))
    return
  }
  if (offscreenMessage.action === "recording.cancelled") {
    sendMessage({ method: "recording.cancelled", params: { tabId: offscreenMessage.tabId } })
  }
}

async function requestTabAttach(params: JsonObject | undefined): Promise<JsonObject> {
  const urlIncludes = optionalStringParam(params, "urlIncludes")?.toLowerCase()
  const titleIncludes = optionalStringParam(params, "titleIncludes")?.toLowerCase()
  const sessionId = optionalStringParam(params, "sessionId")
  const message = optionalStringParam(params, "message") ?? "Allow Browser Control to use this tab?"
  const timeoutMs = optionalNumberParam(params, "timeoutMs") ?? 60_000
  const [targets, allChromeTabs] = await Promise.all([
    chrome.debugger.getTargets(),
    chrome.tabs.query({}).catch(() => [] as chrome.tabs.Tab[]),
  ])
  const tabMeta = new Map<number, { readonly active: boolean; readonly lastAccessed: number; readonly windowId: number }>()
  for (const t of allChromeTabs) {
    if (typeof t.id === "number") {
      tabMeta.set(t.id, {
        active: Boolean(t.active),
        lastAccessed: typeof t.lastAccessed === "number" ? t.lastAccessed : 0,
        windowId: t.windowId,
      })
    }
  }
  const owned = await getOwnedDebuggerTabIds(chrome.debugger)
  const webTargets = targets.filter(
    (t) => t.type === "page" && typeof t.tabId === "number" && /^https?:\/\//i.test(t.url ?? "") && !t.attached && !owned.has(t.tabId),
  )
  // Sort visible active tabs first, ordered by most recently accessed
  webTargets.sort((a, b) => {
    const ma = tabMeta.get(a.tabId!)
    const mb = tabMeta.get(b.tabId!)
    const activeDiff = Number(Boolean(mb?.active)) - Number(Boolean(ma?.active))
    if (activeDiff !== 0) return activeDiff
    return (mb?.lastAccessed ?? 0) - (ma?.lastAccessed ?? 0)
  })
  const matched = webTargets.find((t) => {
    if (urlIncludes && !(t.url ?? "").toLowerCase().includes(urlIncludes)) return false
    if (titleIncludes && !(t.title ?? "").toLowerCase().includes(titleIncludes)) return false
    return true
  })
  if (!matched || typeof matched.tabId !== "number") {
    throw new Error(
      urlIncludes || titleIncludes
        ? `No unattached http(s) browser tab matched ${urlIncludes ?? titleIncludes}`
        : "No unattached http(s) browser tab found",
    )
  }
  const tabId = matched.tabId
  const meta = tabMeta.get(tabId)
  if (meta?.windowId !== undefined) {
    await chrome.windows.update(meta.windowId, { focused: true }).catch(() => {})
  }
  await chrome.tabs.update(tabId, { active: true }).catch(() => {})
  const requestId = `${tabId}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
  let contentScriptReached = false
  try {
    await sendPageStatusMessage(
      tabId,
      {
        action: "tab-request.prompt",
        requestId,
        ...(sessionId ? { sessionId } : {}),
        message,
      },
      true,
    )
    contentScriptReached = true
  } catch {
    contentScriptReached = false
  }
  if (contentScriptReached) {
    const approved = await new Promise<boolean>((resolve) => {
      const timer = setTimeout(() => {
        pendingTabRequests.delete(requestId)
        void sendPageStatusMessage(tabId, { action: "page-status.clear" })
        resolve(false)
      }, timeoutMs)
      pendingTabRequests.set(requestId, (decision) => {
        clearTimeout(timer)
        resolve(decision)
      })
    })
    if (!approved) {
      return { approved: false, tabId, url: matched.url ?? "" }
    }
    try {
      await chrome.debugger.attach({ tabId }, "1.3")
    } catch (error) {
      if (!isAlreadyAttachedError(error)) throw error
    }
    await recordAttachedTab(tabId)
    return { approved: true, tabId, url: matched.url ?? "" }
  }

  // Fallback for tabs opened before the extension was loaded/reloaded (orphaned content script):
  // temporarily attach debugger to render the Dynamic Island approval prompt in-page, and detach if declined.
  try {
    await chrome.debugger.attach({ tabId }, "1.3")
  } catch (error) {
    if (!isAlreadyAttachedError(error)) throw error
  }
  const safeSession = (sessionId || "Browser Control").replace(/[<>&"']/g, "")
  const safeMessage = message.replace(/[<>&"']/g, "")
  const popupHtml = [
    "<style>",
    ":host { all: initial !important; position: fixed !important; top: 10px !important; left: 50% !important; transform: translateX(-50%) !important; z-index: 2147483647 !important; font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif !important; }",
    ".island { box-sizing: border-box; width: 368px; padding: 10px 14px 11px; border-radius: 24px; background: #09090b; border: 1px solid rgba(251, 191, 36, 0.38); box-shadow: 0 10px 28px rgba(0, 0, 0, 0.28), 0 2px 6px rgba(0, 0, 0, 0.16); color: #fafafa; animation: pop 280ms cubic-bezier(0.22, 1.28, 0.36, 1); transform-origin: 50% 0%; }",
    "@keyframes pop { from { opacity: 0; transform: scale3d(0.45, 0.32, 1); filter: blur(5px); } to { opacity: 1; transform: scale3d(1, 1, 1); filter: blur(0px); } }",
    ".hdr { display: flex; align-items: center; gap: 7px; font-size: 10.5px; font-weight: 500; color: rgba(161, 161, 170, 0.9); }",
    ".dot { width: 7px; height: 7px; border-radius: 50%; background: #fbbf24; box-shadow: 0 0 8px #fbbf24; }",
    ".msg { margin: 5px 0 9px; font-size: 12.5px; font-weight: 560; letter-spacing: -0.01em; color: #fafafa; }",
    ".btns { display: flex; gap: 6px; }",
    "button { flex: 1; padding: 6px 12px; border-radius: 999px; border: 1px solid rgba(255,255,255,0.16); font: 600 11.5px/1.2 -apple-system, BlinkMacSystemFont, sans-serif; color: #fff; cursor: pointer; }",
    ".allow { background: linear-gradient(180deg, rgba(245, 158, 11, 0.96), rgba(217, 119, 6, 0.92)); }",
    ".deny { background: rgba(148, 163, 184, 0.16); color: #e2e8f0; }",
    "</style>",
    `<div class="island"><div class="hdr"><span class="dot"></span><span>${safeSession} · requesting tab</span></div><div class="msg">${safeMessage}</div><div class="btns"><button class="allow" type="button">Allow · ⌘↵</button><button class="deny" type="button">Not now</button></div></div>`,
  ].join("")
  const evalResult = await chrome.debugger
    .sendCommand(
      { tabId },
      "Runtime.evaluate",
      {
        awaitPromise: true,
        returnByValue: true,
        expression: `new Promise((resolve) => {
          const existing = document.getElementById("__browser_control_tab_request__");
          if (existing) existing.remove();
          const host = document.createElement("div");
          host.id = "__browser_control_tab_request__";
          const shadow = host.attachShadow({ mode: "open" });
          shadow.innerHTML = ${JSON.stringify(popupHtml)};
          const finish = (ok) => {
            window.removeEventListener("keydown", onKey, true);
            host.remove();
            resolve(ok);
          };
          const onKey = (e) => {
            if (e.key === "Escape") { e.preventDefault(); finish(false); }
            else if ((e.metaKey || e.ctrlKey) && e.key === "Enter") { e.preventDefault(); finish(true); }
          };
          window.addEventListener("keydown", onKey, true);
          shadow.querySelector(".allow").addEventListener("click", () => finish(true));
          shadow.querySelector(".deny").addEventListener("click", () => finish(false));
          document.documentElement.appendChild(host);
          setTimeout(() => finish(false), ${timeoutMs});
        })`,
      },
    )
    .catch(() => ({ result: { value: false } }))
  const approved = (evalResult as { readonly result?: { readonly value?: unknown } })?.result?.value === true
  if (!approved) {
    explicitlyDetachingTabs.add(tabId)
    try {
      await chrome.debugger.detach({ tabId }).catch(() => {})
    } finally {
      explicitlyDetachingTabs.delete(tabId)
    }
    return { approved: false, tabId, url: matched.url ?? "" }
  }
  await recordAttachedTab(tabId)
  return { approved: true, tabId, url: matched.url ?? "" }
}

async function sendPageStatusMessage(tabId: number, message: JsonObject, required = false): Promise<void> {
  try {
    await chrome.tabs.sendMessage(tabId, message)
  } catch (error) {
    if (required) throw error
    // Restricted pages do not accept content scripts. Visibility is best-effort
    // and must never interfere with debugger attachment or detachment.
  }
}

function sendMessage(message: JsonObject): void {
  void sendMessageAfterConnection(message).catch(() => {})
}

async function sendMessageAfterConnection(message: JsonObject): Promise<void> {
  const connected = openSocket()
  if (connected) {
    connected.send(JSON.stringify(message))
    return
  }
  await ensureConnection()
  openSocket()?.send(JSON.stringify(message))
}

function openSocket(): WebSocket | undefined {
  const current = socket
  return current?.readyState === WebSocket.OPEN ? current : undefined
}

async function sendBinaryAfterConnection(data: Uint8Array): Promise<void> {
  if (socket?.readyState !== WebSocket.OPEN) await ensureConnection()
  const currentSocket = socket
  if (currentSocket?.readyState !== WebSocket.OPEN) throw new Error("Browser Control relay is not connected")
  const deadline = Date.now() + 30_000
  while (currentSocket.bufferedAmount + data.byteLength > maxRecordingSocketBufferedBytes) {
    await new Promise((resolve) => setTimeout(resolve, 10))
    if (socket !== currentSocket || currentSocket.readyState !== WebSocket.OPEN) {
      throw new Error("Browser Control relay disconnected while sending recording data")
    }
    if (Date.now() >= deadline) throw new Error("Timed out sending recording data to the Browser Control relay")
  }
  currentSocket.send(new Uint8Array(data))
}

function decodeBase64(value: string): Uint8Array {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index)
  return bytes
}

function isAlreadyAttachedError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error)
  return message.includes("Another debugger is already attached") || message.includes("Debugger is already attached")
}

function numberParam(params: JsonObject | undefined, key: string): number {
  const value = params?.[key]
  if (typeof value !== "number") {
    throw new Error(`Missing number param: ${key}`)
  }
  return value
}

function stringParam(params: JsonObject | undefined, key: string): string {
  const value = params?.[key]
  if (typeof value !== "string") {
    throw new Error(`Missing string param: ${key}`)
  }
  return value
}

function optionalStringParam(params: JsonObject | undefined, key: string): string | undefined {
  const value = params?.[key]
  return typeof value === "string" ? value : undefined
}

function optionalBooleanParam(params: JsonObject | undefined, key: string): boolean | undefined {
  const value = params?.[key]
  return typeof value === "boolean" ? value : undefined
}

function optionalNumberParam(params: JsonObject | undefined, key: string): number | undefined {
  const value = params?.[key]
  return typeof value === "number" ? value : undefined
}

function objectParam(params: JsonObject | undefined, key: string): JsonObject | undefined {
  const value = params?.[key]
  return isJsonObject(value) ? value : undefined
}

function toJsonObject(value: unknown): JsonObject {
  return isJsonObject(value) ? value : {}
}
